image: node:16
pipelines:
  branches:
    master:
      - step:
          name: Build
          script:
            - npm install 
            - npm run build
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $user
                SERVER: $host
                REMOTE_PATH: /var/www/html/
                LOCAL_PATH: build/*